clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next

workspace:
  base: /test
  path: toolkit

matrix:
  PHP_VERSION: 8.1
  COMPOSER_VERSION: 2
  COMPOSER_BOUNDARY:
    - lowest
    - highest

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    environment:
      - DOCUMENT_ROOT=/test/toolkit

pipeline:
  composer-install:
    group: composer
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer self-update --${COMPOSER_VERSION}
      - composer install --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  composer-update-lowest:
    group: composer
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer self-update --${COMPOSER_VERSION}
      - composer update --prefer-lowest --prefer-stable --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  phpcs:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    commands:
      - ./vendor/bin/phpcs -i
      - ./vendor/bin/phpcs -p

  phpunit:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    commands:
      - ./vendor/bin/phpunit

  lint-yaml:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    secrets: [ github_api_token, composer_auth ]
    commands:
      - CONFIG_FOLDER=$(if test -d config; then find config -type f -name "*.yml"; fi)
      - if ! [ -z "$CONFIG_FOLDER" ]; then ./vendor/bin/yaml-lint $CONFIG_FOLDER; fi
      - LIB_FOLDER=$(if test -d lib; then find lib -type f -name "*.yml"; fi)
      - if ! [ -z "$LIB_FOLDER" ]; then ./vendor/bin/yaml-lint $LIB_FOLDER; fi

  lint-php:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=8.1}-ci
    secrets: [ github_api_token, composer_auth ]
    commands:
      - ./vendor/bin/parallel-lint --exclude web --exclude vendor -e module -e inc -e theme -e install -e php .
