command:
  toolkit:
    options:
      root: ${drupal.root}
    build-dist:
      options:
        dist-root: ${toolkit.build.dist.root}
        keep: ${toolkit.build.dist.keep}
        remove: ${toolkit.build.dist.remove}
    build-assets:
      options:
        default-theme: ${drupal.site.default_theme}
        custom-code-folder: ${toolkit.build.custom-code-folder}
        build-npm-packages: ${toolkit.build.npm.packages}
        build-npm-mode: ${toolkit.build.npm.mode}
        validate: ${toolkit.scss.validate}
        theme-task-runner: ${toolkit.build.npm.theme-task-runner}
