command:
  toolkit:
    test-behat:
      options:
        from: ${toolkit.test.behat.from}
        to: ${toolkit.test.behat.to}
        profile: ${toolkit.test.behat.profile}
        options: ${toolkit.test.behat.options}
    test-phpunit:
      options:
        execution: ${toolkit.test.phpunit.execution}
        from: ${toolkit.test.phpunit.from}
        to: ${toolkit.test.phpunit.to}
