command:
  toolkit:
    test-behat:
      options:
        from: ${toolkit.test.behat.from}
        to: ${toolkit.test.behat.to}
    test-phpunit:
      options:
        execution: ${toolkit.test.phpunit.execution}
        from: ${toolkit.test.phpunit.from}
        to: ${toolkit.test.phpunit.to}
    setup-eslint:
      options:
        config: ${toolkit.lint.eslint.config}
        ignores: ${toolkit.lint.eslint.ignores}
        drupal-root: ${drupal.root}
        packages: ${toolkit.lint.eslint.packages}
    lint-yaml:
      options:
        config: ${toolkit.lint.eslint.config}
        extensions: ${toolkit.lint.eslint.extensions_yaml}
    lint-js:
      options:
        config: ${toolkit.lint.eslint.config}
        extensions: ${toolkit.lint.eslint.extensions_js}
